language: python
python:
- "2.7"

cache: pip

services:
- postgresql

addons:
  postgresql: "9.5"

env:
  global: 
  - PLUGIN_DIR: aiida-diff
  
  matrix:
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: tests
  - TEST_AIIDA_BACKEND: sqlalchemy
    TEST_TYPE: tests
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: docs
    READTHEDOCS: 'True'
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: pre-commit
  - TEST_AIIDA_BACKEND: django
    TEST_TYPE: tests
    AIIDA_BRANCH: develop
    
  allow_failures: 
  - PLUGIN_DIR: aiida-diff
    TEST_AIIDA_BACKEND: django
    TEST_TYPE: tests
    AIIDA_BRANCH: develop

install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install cookiecutter
- cookiecutter --no-input .
- pip install -e ${PLUGIN_DIR}[docs,pre-commit,testing]
- >
  if [[ ! -z "${AIIDA_BRANCH}" ]]; then
    cur_path="$(pwd)";
    cd ..;
    git clone --branch=${AIIDA_BRANCH} https://github.com/aiidateam/aiida_core.git;
    cd aiida_core;
    pip install -U .[testing];
    cd "$cur_path";
  fi

script:
- .travis-data/script.sh
